use_frameworks!

platform :ios, '10.0'

target 'DiscussionSDK_Example' do
  pod 'DiscussionSDK', :path => '../'

  target 'DiscussionSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
